apiVersion: apps/v1
kind: Deployment
metadata:
  name: retex-bot
  labels:
    app: retex-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retex-bot
  template:
    metadata:
      labels:
        app: retex-bot
    spec:
      serviceAccountName: retex-bot-sa
      containers:
      - name: retex-bot
        image: retex-bot:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: retex-bot-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: retex-bot-secrets
type: Opaque
stringData:
  DISCORD_TOKEN: "" # This will be filled in via kubectl or a secrets management tool
